language: c

os: linux
dist: trusty
sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tools/apt-get-install-deps.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tools/brew-install-deps.sh; fi

script:
  - tools/build.py --tests

env:
  matrix:
    - OPTS="host-linux" TARGET_OS="linux"
    - OPTS="--test=external-modules"
    - OPTS="--test=no-snapshot"

matrix:
  include:
    - os: osx
      env: OPTS="--test=host-darwin"
  fast_finish: true
